export type Site = {
  title: string;
  url: string;
  author: string;
  num_comment: number;
  points: number;
  objectID: number;
};

export const list: Site[] = [
  {
    title: "React",
    url: "https://react.dev/",
    author: "Jordan Walke",
    num_comment: 3,
    points: 4,
    objectID: 0,
  },
  {
    title: "Redux",
    url: "https://redux.js.org",
    author: "Dan Abramov, Andrew Clark",
    num_comment: 2,
    points: 5,
    objectID: 1,
  },
  {
    title: "TypeScript",
    url: "https://www.typescriptlang.org/",
    author: "Anders Hejlsberg",
    num_comment: 12,
    points: 18,
    objectID: 2,
  },
  {
    title: "Vite",
    url: "https://vitejs.dev/",
    author: "Evan You",
    num_comment: 7,
    points: 14,
    objectID: 3,
  },
  {
    title: "Next.js",
    url: "https://nextjs.org/",
    author: "Guillermo Rauch",
    num_comment: 21,
    points: 33,
    objectID: 4,
  },
  {
    title: "React Router",
    url: "https://reactrouter.com/",
    author: "Ryan Florence, Michael Jackson",
    num_comment: 9,
    points: 16,
    objectID: 5,
  },
  {
    title: "TanStack Query",
    url: "https://tanstack.com/query/latest",
    author: "Tanner Linsley",
    num_comment: 5,
    points: 13,
    objectID: 6,
  },
  {
    title: "Zustand",
    url: "https://zustand-demo.pmnd.rs/",
    author: "Daishi Kato",
    num_comment: 4,
    points: 11,
    objectID: 7,
  },
  {
    title: "MobX",
    url: "https://mobx.js.org/",
    author: "Michel Weststrate",
    num_comment: 6,
    points: 10,
    objectID: 8,
  },
  {
    title: "Recoil",
    url: "https://recoiljs.org/",
    author: "Dave McCabe",
    num_comment: 8,
    points: 9,
    objectID: 9,
  },
  {
    title: "SWR",
    url: "https://swr.vercel.app/",
    author: "Shu Ding",
    num_comment: 3,
    points: 8,
    objectID: 10,
  },
  {
    title: "Node.js",
    url: "https://nodejs.org/",
    author: "Ryan Dahl",
    num_comment: 15,
    points: 22,
    objectID: 11,
  },
  {
    title: "Deno",
    url: "https://deno.com/",
    author: "Ryan Dahl",
    num_comment: 10,
    points: 17,
    objectID: 12,
  },
  {
    title: "Bun",
    url: "https://bun.sh/",
    author: "Jarred Sumner",
    num_comment: 11,
    points: 19,
    objectID: 13,
  },
  {
    title: "Jest",
    url: "https://jestjs.io/",
    author: "Christoph Nakazawa",
    num_comment: 14,
    points: 20,
    objectID: 14,
  },
  {
    title: "Vitest",
    url: "https://vitest.dev/",
    author: "Anthony Fu",
    num_comment: 6,
    points: 12,
    objectID: 15,
  },
  {
    title: "Testing Library",
    url: "https://testing-library.com/",
    author: "Kent C. Dodds",
    num_comment: 5,
    points: 10,
    objectID: 16,
  },
  {
    title: "Tailwind CSS",
    url: "https://tailwindcss.com/",
    author: "Adam Wathan",
    num_comment: 18,
    points: 27,
    objectID: 17,
  },
  {
    title: "MDN Web Docs",
    url: "https://developer.mozilla.org/",
    author: "Chris Mills",
    num_comment: 25,
    points: 40,
    objectID: 18,
  },
  {
    title: "ESLint",
    url: "https://eslint.org/",
    author: "Nicholas C. Zakas",
    num_comment: 13,
    points: 15,
    objectID: 19,
  },
  {
    title: "Prettier",
    url: "https://prettier.io/",
    author: "James Long",
    num_comment: 9,
    points: 14,
    objectID: 20,
  },
  {
    title: "Webpack",
    url: "https://webpack.js.org/",
    author: "Tobias Koppers",
    num_comment: 16,
    points: 21,
    objectID: 21,
  },

  // +35 more dummy items
  {
    title: "Spring Boot",
    url: "https://spring.io/projects/spring-boot",
    author: "Phillip Webb, Dave Syer",
    num_comment: 19,
    points: 28,
    objectID: 22,
  },
  {
    title: "Express",
    url: "https://expressjs.com/",
    author: "TJ Holowaychuk",
    num_comment: 14,
    points: 18,
    objectID: 23,
  },
  {
    title: "Fastify",
    url: "https://www.fastify.io/",
    author: "Matteo Collina",
    num_comment: 7,
    points: 15,
    objectID: 24,
  },
  {
    title: "NestJS",
    url: "https://nestjs.com/",
    author: "Kamil Myśliwiec",
    num_comment: 10,
    points: 17,
    objectID: 25,
  },
  {
    title: "Django",
    url: "https://www.djangoproject.com/",
    author: "Adrian Holovaty, Simon Willison",
    num_comment: 22,
    points: 31,
    objectID: 26,
  },
  {
    title: "Flask",
    url: "https://flask.palletsprojects.com/",
    author: "Armin Ronacher",
    num_comment: 13,
    points: 16,
    objectID: 27,
  },
  {
    title: "FastAPI",
    url: "https://fastapi.tiangolo.com/",
    author: "Sebastián Ramírez",
    num_comment: 18,
    points: 29,
    objectID: 28,
  },
  {
    title: "Ruby on Rails",
    url: "https://rubyonrails.org/",
    author: "David Heinemeier Hansson",
    num_comment: 15,
    points: 23,
    objectID: 29,
  },
  {
    title: "Laravel",
    url: "https://laravel.com/",
    author: "Taylor Otwell",
    num_comment: 12,
    points: 19,
    objectID: 30,
  },
  {
    title: "Phoenix",
    url: "https://www.phoenixframework.org/",
    author: "Chris McCord",
    num_comment: 8,
    points: 14,
    objectID: 31,
  },
  {
    title: "ASP.NET Core",
    url: "https://dotnet.microsoft.com/apps/aspnet",
    author: "David Fowler",
    num_comment: 17,
    points: 26,
    objectID: 32,
  },
  {
    title: "Ktor",
    url: "https://ktor.io/",
    author: "Roman Elizarov",
    num_comment: 6,
    points: 13,
    objectID: 33,
  },
  {
    title: "Quarkus",
    url: "https://quarkus.io/",
    author: "Emmanuel Bernard, Clément Escoffier",
    num_comment: 9,
    points: 16,
    objectID: 34,
  },
  {
    title: "Micronaut",
    url: "https://micronaut.io/",
    author: "Graeme Rocher",
    num_comment: 5,
    points: 12,
    objectID: 35,
  },
  {
    title: "Axum",
    url: "https://docs.rs/axum/",
    author: "David Pedersen",
    num_comment: 11,
    points: 20,
    objectID: 36,
  },
  {
    title: "Actix Web",
    url: "https://actix.rs/",
    author: "Nikolay Kim",
    num_comment: 10,
    points: 18,
    objectID: 37,
  },
  {
    title: "Gin",
    url: "https://gin-gonic.com/",
    author: "Manu Uhl",
    num_comment: 7,
    points: 15,
    objectID: 38,
  },
  {
    title: "Fiber",
    url: "https://gofiber.io/",
    author: "Fenny (gofiber)",
    num_comment: 6,
    points: 14,
    objectID: 39,
  },
  {
    title: "Go",
    url: "https://go.dev/",
    author: "Robert Griesemer, Rob Pike, Ken Thompson",
    num_comment: 20,
    points: 34,
    objectID: 40,
  },
  {
    title: "Rust",
    url: "https://www.rust-lang.org/",
    author: "Graydon Hoare",
    num_comment: 23,
    points: 38,
    objectID: 41,
  },
  {
    title: "Python",
    url: "https://www.python.org/",
    author: "Guido van Rossum",
    num_comment: 30,
    points: 45,
    objectID: 42,
  },
  {
    title: "Java",
    url: "https://www.oracle.com/java/",
    author: "James Gosling",
    num_comment: 26,
    points: 39,
    objectID: 43,
  },
  {
    title: "Kotlin",
    url: "https://kotlinlang.org/",
    author: "Andrey Breslav",
    num_comment: 12,
    points: 21,
    objectID: 44,
  },
  {
    title: "C",
    url: "https://en.wikipedia.org/wiki/C_(programming_language)",
    author: "Dennis Ritchie",
    num_comment: 28,
    points: 44,
    objectID: 45,
  },
  {
    title: "C++",
    url: "https://isocpp.org/",
    author: "Bjarne Stroustrup",
    num_comment: 24,
    points: 36,
    objectID: 46,
  },
  {
    title: "Zig",
    url: "https://ziglang.org/",
    author: "Andrew Kelley",
    num_comment: 9,
    points: 17,
    objectID: 47,
  },
  {
    title: "Swift",
    url: "https://www.swift.org/",
    author: "Chris Lattner",
    num_comment: 8,
    points: 16,
    objectID: 48,
  },
  {
    title: "Haskell",
    url: "https://www.haskell.org/",
    author: "Paul Hudak, Philip Wadler, Simon Peyton Jones",
    num_comment: 7,
    points: 13,
    objectID: 49,
  },
  {
    title: "Linux",
    url: "https://www.kernel.org/",
    author: "Linus Torvalds",
    num_comment: 29,
    points: 41,
    objectID: 50,
  },
  {
    title: "FreeBSD",
    url: "https://www.freebsd.org/",
    author: "Jordan Hubbard, Nate Williams",
    num_comment: 16,
    points: 27,
    objectID: 51,
  },
  {
    title: "OpenBSD",
    url: "https://www.openbsd.org/",
    author: "Theo de Raadt",
    num_comment: 11,
    points: 19,
    objectID: 52,
  },
  {
    title: "NetBSD",
    url: "https://www.netbsd.org/",
    author: "Chris Demetriou",
    num_comment: 6,
    points: 12,
    objectID: 53,
  },
  {
    title: "macOS",
    url: "https://www.apple.com/macos/",
    author: "Avie Tevanian",
    num_comment: 13,
    points: 20,
    objectID: 54,
  },
  {
    title: "Windows",
    url: "https://www.microsoft.com/windows",
    author: "Dave Cutler",
    num_comment: 21,
    points: 30,
    objectID: 55,
  },
  {
    title: "PostgreSQL",
    url: "https://www.postgresql.org/",
    author: "Michael Stonebraker, Bruce Momjian",
    num_comment: 17,
    points: 28,
    objectID: 56,
  },
  {
    title: "MySQL",
    url: "https://www.mysql.com/",
    author: "Michael 'Monty' Widenius, David Axmark",
    num_comment: 14,
    points: 22,
    objectID: 57,
  },
  {
    title: "illumos",
    url: "https://illumos.org/",
    author: "Bryan Cantrill",
    num_comment: 9,
    points: 17,
    objectID: 58,
  },
  {
    title: "OpenIndiana",
    url: "https://www.openindiana.org/",
    author: "Alasdair Lumsden",
    num_comment: 6,
    points: 12,
    objectID: 59,
  },
  {
    title: "OmniOS",
    url: "https://omnios.org/",
    author: "Dan McDonald",
    num_comment: 5,
    points: 11,
    objectID: 60,
  },
  {
    title: "Tribblix",
    url: "https://tribblix.org/",
    author: "Peter Tribble",
    num_comment: 4,
    points: 9,
    objectID: 61,
  },
  {
    title: "SmartOS",
    url: "https://smartos.org/",
    author: "Bryan Cantrill",
    num_comment: 7,
    points: 14,
    objectID: 62,
  },
  // +25 more (filesystems, IDEs/editors, tooling)
  {
    title: "ZFS",
    url: "https://openzfs.org/",
    author: "Jeff Bonwick, Matt Ahrens",
    num_comment: 22,
    points: 41,
    objectID: 63,
  },
  {
    title: "Btrfs",
    url: "https://btrfs.readthedocs.io/",
    author: "Chris Mason",
    num_comment: 14,
    points: 26,
    objectID: 64,
  },
  {
    title: "ext4",
    url: "https://en.wikipedia.org/wiki/Ext4",
    author: "Theodore Ts'o",
    num_comment: 18,
    points: 30,
    objectID: 65,
  },
  {
    title: "UFS/FFS",
    url: "https://en.wikipedia.org/wiki/Unix_File_System",
    author: "Marshall Kirk McKusick",
    num_comment: 11,
    points: 21,
    objectID: 66,
  },
  {
    title: "APFS",
    url: "https://en.wikipedia.org/wiki/Apple_File_System",
    author: "Dominic Giampaolo",
    num_comment: 9,
    points: 19,
    objectID: 67,
  },
  {
    title: "NTFS",
    url: "https://en.wikipedia.org/wiki/NTFS",
    author: "Gary Kimura",
    num_comment: 13,
    points: 24,
    objectID: 68,
  },
  {
    title: "FUSE",
    url: "https://github.com/libfuse/libfuse",
    author: "Miklós Szeredi",
    num_comment: 8,
    points: 16,
    objectID: 69,
  },
  {
    title: "Bcachefs",
    url: "https://bcachefs.org/",
    author: "Kent Overstreet",
    num_comment: 12,
    points: 23,
    objectID: 70,
  },
  {
    title: "SquashFS",
    url: "https://en.wikipedia.org/wiki/SquashFS",
    author: "Phillip Lougher",
    num_comment: 6,
    points: 12,
    objectID: 71,
  },
  {
    title: "F2FS",
    url: "https://en.wikipedia.org/wiki/F2FS",
    author: "Jaegeuk Kim",
    num_comment: 7,
    points: 13,
    objectID: 72,
  },
  {
    title: "Ceph",
    url: "https://ceph.io/en/",
    author: "Sage Weil",
    num_comment: 17,
    points: 29,
    objectID: 73,
  },
  {
    title: "Vim",
    url: "https://www.vim.org/",
    author: "Bram Moolenaar",
    num_comment: 20,
    points: 35,
    objectID: 74,
  },
  {
    title: "GNU Emacs",
    url: "https://www.gnu.org/software/emacs/",
    author: "Richard Stallman",
    num_comment: 16,
    points: 27,
    objectID: 75,
  },
  {
    title: "Neovim",
    url: "https://neovim.io/",
    author: "Thiago de Arruda",
    num_comment: 15,
    points: 28,
    objectID: 76,
  },
  {
    title: "Visual Studio Code",
    url: "https://code.visualstudio.com/",
    author: "Erich Gamma",
    num_comment: 24,
    points: 39,
    objectID: 77,
  },
  {
    title: "Sublime Text",
    url: "https://www.sublimetext.com/",
    author: "Jon Skinner",
    num_comment: 10,
    points: 18,
    objectID: 78,
  },
  {
    title: "Atom",
    url: "https://github.com/atom/atom",
    author: "Nathan Sobo",
    num_comment: 9,
    points: 15,
    objectID: 79,
  },
  {
    title: "Notepad++",
    url: "https://notepad-plus-plus.org/",
    author: "Don Ho",
    num_comment: 12,
    points: 17,
    objectID: 80,
  },
  {
    title: "CMake",
    url: "https://cmake.org/",
    author: "Bill Hoffman",
    num_comment: 14,
    points: 22,
    objectID: 81,
  },
  {
    title: "Ninja",
    url: "https://ninja-build.org/",
    author: "Evan Martin",
    num_comment: 8,
    points: 14,
    objectID: 82,
  },
  {
    title: "GNU Make",
    url: "https://www.gnu.org/software/make/",
    author: "Stuart Feldman",
    num_comment: 11,
    points: 16,
    objectID: 83,
  },
  {
    title: "Git",
    url: "https://git-scm.com/",
    author: "Linus Torvalds",
    num_comment: 28,
    points: 46,
    objectID: 84,
  },
  {
    title: "Mercurial",
    url: "https://www.mercurial-scm.org/",
    author: "Matt Mackall",
    num_comment: 7,
    points: 12,
    objectID: 85,
  },
  {
    title: "Docker",
    url: "https://www.docker.com/",
    author: "Solomon Hykes",
    num_comment: 19,
    points: 31,
    objectID: 86,
  },
  {
    title: "Kubernetes",
    url: "https://kubernetes.io/",
    author: "Joe Beda, Craig McLuckie, Brendan Burns",
    num_comment: 23,
    points: 37,
    objectID: 87,
  },
  // +30 more (editors/IDEs, tools, networking, storage, etc.)
  {
    title: "Gosling Emacs (Gosmacs)",
    url: "https://en.wikipedia.org/wiki/Gosling_Emacs",
    author: "James Gosling",
    num_comment: 6,
    points: 13,
    objectID: 88,
  },
  {
    title: "nano",
    url: "https://www.nano-editor.org/",
    author: "Chris Allegretta",
    num_comment: 5,
    points: 9,
    objectID: 89,
  },
  {
    title: "Helix",
    url: "https://helix-editor.com/",
    author: "Maurice Borensztein",
    num_comment: 7,
    points: 12,
    objectID: 90,
  },
  {
    title: "Kakoune",
    url: "https://kakoune.org/",
    author: "Maël Nison",
    num_comment: 4,
    points: 10,
    objectID: 91,
  },
  {
    title: "tmux",
    url: "https://github.com/tmux/tmux",
    author: "Nicholas Marriott",
    num_comment: 10,
    points: 18,
    objectID: 92,
  },
  {
    title: "OpenSSH",
    url: "https://www.openssh.com/",
    author: "Tatu Ylönen",
    num_comment: 14,
    points: 26,
    objectID: 93,
  },
  {
    title: "WireGuard",
    url: "https://www.wireguard.com/",
    author: "Jason A. Donenfeld",
    num_comment: 13,
    points: 24,
    objectID: 94,
  },
  {
    title: "Wireshark",
    url: "https://www.wireshark.org/",
    author: "Gerald Combs",
    num_comment: 11,
    points: 19,
    objectID: 95,
  },
  {
    title: "tcpdump",
    url: "https://www.tcpdump.org/",
    author: "Van Jacobson",
    num_comment: 8,
    points: 15,
    objectID: 96,
  },
  {
    title: "curl",
    url: "https://curl.se/",
    author: "Daniel Stenberg",
    num_comment: 12,
    points: 22,
    objectID: 97,
  },
  {
    title: "OpenSSL",
    url: "https://www.openssl.org/",
    author: "Eric A. Young, Tim Hudson",
    num_comment: 9,
    points: 17,
    objectID: 98,
  },
  {
    title: "LibreSSL",
    url: "https://www.libressl.org/",
    author: "Theo de Raadt",
    num_comment: 6,
    points: 12,
    objectID: 99,
  },
  {
    title: "LLVM/Clang",
    url: "https://llvm.org/",
    author: "Chris Lattner",
    num_comment: 16,
    points: 31,
    objectID: 100,
  },
  {
    title: "GCC",
    url: "https://gcc.gnu.org/",
    author: "Richard Stallman",
    num_comment: 18,
    points: 33,
    objectID: 101,
  },
  {
    title: "Valgrind",
    url: "https://valgrind.org/",
    author: "Julian Seward",
    num_comment: 10,
    points: 18,
    objectID: 102,
  },
  {
    title: "SQLite",
    url: "https://www.sqlite.org/",
    author: "D. Richard Hipp",
    num_comment: 15,
    points: 28,
    objectID: 103,
  },
  {
    title: "Redis",
    url: "https://redis.io/",
    author: "Salvatore Sanfilippo",
    num_comment: 13,
    points: 25,
    objectID: 104,
  },
  {
    title: "LevelDB",
    url: "https://github.com/google/leveldb",
    author: "Jeff Dean, Sanjay Ghemawat",
    num_comment: 9,
    points: 16,
    objectID: 105,
  },
  {
    title: "RocksDB",
    url: "https://rocksdb.org/",
    author: "Dhruba Borthakur",
    num_comment: 8,
    points: 15,
    objectID: 106,
  },
  {
    title: "LMDB",
    url: "https://www.openldap.org/software/repo.html",
    author: "Howard Chu",
    num_comment: 6,
    points: 13,
    objectID: 107,
  },
  {
    title: "Zstandard (zstd)",
    url: "https://facebook.github.io/zstd/",
    author: "Yann Collet",
    num_comment: 11,
    points: 21,
    objectID: 108,
  },
  {
    title: "ReiserFS",
    url: "https://en.wikipedia.org/wiki/ReiserFS",
    author: "Hans Reiser",
    num_comment: 7,
    points: 12,
    objectID: 109,
  },
  {
    title: "NILFS2",
    url: "https://en.wikipedia.org/wiki/NILFS",
    author: "Ryusuke Konishi",
    num_comment: 4,
    points: 9,
    objectID: 110,
  },
  {
    title: "QEMU",
    url: "https://www.qemu.org/",
    author: "Fabrice Bellard",
    num_comment: 12,
    points: 23,
    objectID: 111,
  },
  {
    title: "VirtualBox",
    url: "https://www.virtualbox.org/",
    author: "Innotek (originally by Weinig & Klose)",
    num_comment: 8,
    points: 14,
    objectID: 112,
  },
  {
    title: "OpenZFS",
    url: "https://openzfs.org/",
    author: "Jeff Bonwick, Matt Ahrens",
    num_comment: 17,
    points: 32,
    objectID: 113,
  },
  {
    title: "Bhyve",
    url: "https://bhyve.org/",
    author: "Peter Grehan",
    num_comment: 6,
    points: 12,
    objectID: 114,
  },
  {
    title: "DTrace",
    url: "https://en.wikipedia.org/wiki/DTrace",
    author: "Bryan Cantrill, Adam Leventhal, Mike Shapiro",
    num_comment: 14,
    points: 27,
    objectID: 115,
  },
  {
    title: "Cython",
    url: "https://cython.org/",
    author: "Robert Bradshaw, Stefan Behnel",
    num_comment: 5,
    points: 11,
    objectID: 116,
  },
  {
    title: "Bazel",
    url: "https://bazel.build/",
    author: "László Molnár",
    num_comment: 9,
    points: 16,
    objectID: 117,
  },
  {
    title: "vi",
    url: "https://en.wikipedia.org/wiki/Vi",
    author: "Bill Joy",
    num_comment: 12,
    points: 24,
    objectID: 118,
  },
];
